// <auto-generated />
using FarmStand.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmStand.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220501151944_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FarmStand.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Sweet Fruits",
                            CategoryName = "Fruit"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Vegetables ",
                            CategoryName = "Root Vegetables"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Savory Fruits",
                            CategoryName = "Seeded Vegetables"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Underground Produce",
                            CategoryName = "Root Vegetables"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Aromatic Leaves",
                            CategoryName = "Herbs"
                        });
                });

            modelBuilder.Entity("FarmStand.Models.Produce", b =>
                {
                    b.Property<int>("ProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProduceOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProduceId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Produce");

                    b.HasData(
                        new
                        {
                            ProduceId = 1,
                            CategoryId = 1,
                            ImageUrl = "",
                            IsProduceOfTheWeek = false,
                            Name = "Strawberries",
                            Price = 4.99m
                        },
                        new
                        {
                            ProduceId = 2,
                            CategoryId = 2,
                            ImageUrl = "",
                            IsProduceOfTheWeek = false,
                            Name = "Onions",
                            Price = 1.99m
                        },
                        new
                        {
                            ProduceId = 3,
                            CategoryId = 3,
                            ImageUrl = "",
                            IsProduceOfTheWeek = true,
                            Name = "Cucumbers",
                            Price = 3.99m
                        });
                });

            modelBuilder.Entity("FarmStand.Models.Produce", b =>
                {
                    b.HasOne("FarmStand.Models.Category", "Category")
                        .WithMany("ProduceList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FarmStand.Models.Category", b =>
                {
                    b.Navigation("ProduceList");
                });
#pragma warning restore 612, 618
        }
    }
}
